name: Compile LaTex

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Convert example.tex
      uses: xu-cheng/latex-action@master
      with:
        root_file: example.tex
        working_directory: ../../dissertation/